void zmath(double num1,double num2);
void printe(std::string printout);
void loops(std::string wordtl,int ltimes);
void help();
void kcal(double kcalm);
void end();
void github();
void clearc();
void sleep(double sleeptime);
void exit (int status);